image: microsoft/dotnet:2.1-sdk-alpine

stages:
  - build
  - test-pack
  - deploy

cache:
  key: "$CI_PIPELINE_ID"

build:
  stage: build
  script:
    - dotnet build --configuration Release
  artifacts:
    untracked: true

test:
  stage: test-pack
  script:
    - dotnet test --configuration Release ./unit/Test.csproj

pack:
  stage: test-pack
  script:
    - dotnet pack --configuration Release --output "$(pwd)/dist/"
  artifacts:
    untracked: false
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - dotnet nuget push ./dist/*.nupkg --api-key $NUGET_API_KEY
  only:
    - master
